apiVersion: 1

datasources:
  - name: ForecastPostgres
    type: postgres
    access: proxy
    isDefault: false
    editable: true
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      connMaxLifetime: 14400
      maxOpenConns: 100
      maxIdleConns: 10
